"""Supervisor integration — install/start/stop/status/uninstall (OS-agnostic orchestration).

The OS-specific bits (rendering the job definition, driving launchctl or systemctl) live behind
the platform seam; everything here (mode logic, config recording, ours-vs-foreign refusal) is
portable. Start-on-login is expressed by job-file *placement*, not by a toggle inside the file:
login-start mode places it in the supervisor's auto-start dir (launchd loads it at login, systemd
is told to enable it); manual mode keeps it in the config dir and registers it only on demand.
Crash keep-alive is identical in both modes once registered.

None of that exists in a container, where Docker is the supervisor and its restart policy is the
keep-alive. Only the status report survives there, answered from the instance lock instead of
from a job — the install/start/stop verbs refuse before they reach this module.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path

from sellee import config, deployment, heartbeat, lock, paths
from sellee.db import connect_reader
from sellee.events import query_events
from sellee.installer import materialize
from sellee.platform import Platform, get_platform

# Embedded in every job definition we render, so a re-install/flip only ever touches our own
# file and never silently replaces a foreign (e.g. legacy) daemon's job with the same label.
MARKER = "Generated by sellee. DO NOT EDIT."

LOGIN_START = "login-start"
MANUAL = "manual"

# What `daemon status` calls the worker where there is no supervisor job to take a label from.
APP_LABEL = "sellee"


def _resolve_platform(platform: Platform | None) -> Platform:
    return platform if platform is not None else get_platform()


def job_interpreter() -> Path:
    """The interpreter to name in the job definition.

    Through `current` rather than the version behind it, so the definition stays true across an
    update. Falls back to whatever is running us when there is no venv — a checkout pointed at by
    `./setup --dev` before bootstrapping — because naming an interpreter that does not exist gives
    a job that fails to start with nothing explaining why, and the launcher re-execs onto the venv
    by itself once there is one.
    """
    interpreter = paths.venv_python(paths.current())
    return interpreter if interpreter.exists() else Path(os.path.realpath(sys.executable))


def _resolve_label(platform: Platform, label: str | None) -> str:
    if label:
        return label
    return config.load().daemon_label or platform.default_label()


def _is_ours(path: Path) -> bool:
    try:
        return MARKER in path.read_text()
    except OSError:
        return False


# What a supervised job's PATH is when its definition names none. Spelled out because naming a
# PATH in the definition replaces this rather than extending it — and because the installer's gates
# verify the browser server can be spawned under exactly this, plus the recorded fragment.
SUPERVISED_PATH = "/usr/bin:/bin:/usr/sbin:/sbin"


def _job_environment() -> dict:
    """The environment the supervised daemon is given.

    A supervised job inherits nothing from the shell that installed it, so everything the daemon
    cannot work without is pinned into its definition. Two things qualify. The XDG overrides that
    were in force shaped every path this install provisioned, and a daemon resolving different
    ones would be reading a different machine's state. And the recorded node path fragment — one or
    more directories, colon-joined: neither `node` nor `npx` is on the default PATH above (a version
    manager keeps them somewhere only an interactive shell knows about), so without it the browser
    server cannot be spawned at all.
    """
    env = dict(paths.xdg_overrides())
    node_bin_dir = config.load().node_bin_dir
    if node_bin_dir:
        env["PATH"] = f"{node_bin_dir}:{SUPERVISED_PATH}"
    return env


def _job_locations(platform: Platform, label: str) -> dict:
    filename = platform.supervisor_filename(label)
    return {
        LOGIN_START: paths.launch_agents_dir(platform=platform) / filename,
        MANUAL: paths.config_dir() / filename,
    }


def _find_installed(platform: Platform, label: str) -> Path | None:
    for location in _job_locations(platform, label).values():
        if location.exists() and _is_ours(location):
            return location
    return None


def install(*, mode: str, label: str | None = None, platform: Platform | None = None) -> int:
    platform = _resolve_platform(platform)
    # The recorded label, not the default one — otherwise an install with a custom label writes
    # and registers a *second* job under the default name, leaving the original loaded and two
    # daemons writing one database.
    label = _resolve_label(platform, label)
    locations = _job_locations(platform, label)

    # Refuse if a foreign job file with our label already occupies either target location.
    for location in locations.values():
        if location.exists() and not _is_ours(location):
            print(
                f"refusing to install: a job file labelled {label!r} at {location} was not "
                f"written by sellee — remove it first (never replacing a foreign "
                f"daemon's job).",
                file=sys.stderr,
            )
            return 2

    try:
        materialize.ensure_current(materialize.source_tree())
    except materialize.LayoutError as exc:
        print(f"refusing to install: {exc.message}", file=sys.stderr)
        if exc.fix:
            print(exc.fix, file=sys.stderr)
        return 2

    program_args = [
        str(job_interpreter()),
        str(paths.current() / "bin" / "sellee"),
        "daemon",
        "run",
    ]
    job_text = platform.render_supervisor(
        label=label,
        program_args=program_args,
        stdout_path=paths.logs_dir() / "agent.out.log",
        stderr_path=paths.logs_dir() / "agent.err.log",
        marker=MARKER,
        environment=_job_environment(),
    )

    # Remove any of our own job files from the other location (a mode flip moves the file).
    for other_mode, location in locations.items():
        if other_mode != mode and location.exists() and _is_ours(location):
            if platform.is_registered(label):
                platform.unregister(label)
            location.unlink()

    dest = locations[mode]
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(job_text)
    config.merge_into_file({"daemon_mode": mode, "daemon_label": label})

    if mode == LOGIN_START:
        platform.register(dest)
        print(f"installed (auto-start at login) and started; job file at {dest}")
    else:
        print(f"installed (manual mode); start with: sellee daemon start\njob file at {dest}")
    return 0


def start(*, label: str | None = None, platform: Platform | None = None) -> int:
    platform = _resolve_platform(platform)
    label = _resolve_label(platform, label)
    job = _find_installed(platform, label)
    if job is None:
        print(
            "not installed — run: sellee daemon install --login-start|--manual",
            file=sys.stderr,
        )
        return 2
    if platform.is_registered(label):
        print("already running")
        return 0
    platform.register(job)
    print("started")
    return 0


def stop(*, label: str | None = None, platform: Platform | None = None) -> int:
    platform = _resolve_platform(platform)
    label = _resolve_label(platform, label)
    if not platform.is_registered(label):
        print("not running")
        return 0
    platform.unregister(label)
    print("stopped")
    return 0


def uninstall(*, label: str | None = None, platform: Platform | None = None) -> int:
    platform = _resolve_platform(platform)
    label = _resolve_label(platform, label)
    if platform.is_registered(label):
        platform.unregister(label)
    for location in _job_locations(platform, label).values():
        if location.exists() and _is_ours(location):
            location.unlink()
    print("uninstalled supervisor")
    return 0


@dataclass
class Status:
    label: str
    mode: str
    registered: bool
    heartbeat_age_sec: float | None
    recent_events: list
    channel_bound: bool
    channel_adapter: str | None
    paused: bool
    queued_notices: int
    # Whether a daemon process is actually alive. `registered` only says the supervisor holds a job
    # definition, which stays true across a clean stop — so on its own it reports "running" about a
    # machine where nothing is running. Last, because everything above it is required.
    process_alive: bool = False


def _channel_snapshot() -> dict:
    """Read channel-bound / paused / queued-notice state from sellee.db over a read-only connection
    (the daemon's WAL DB allows a concurrent reader). Degrades to all-false when the DB or the
    channel tables are not present yet, so `daemon status` never errors on a fresh install."""
    import sqlite3

    db = paths.sellee_db()
    default = {
        "channel_bound": False,
        "channel_adapter": None,
        "paused": False,
        "queued_notices": 0,
    }
    if not db.exists():
        return default
    conn = connect_reader(db)
    try:
        ch = conn.execute("SELECT chat_id, adapter FROM channel WHERE id = 1").fetchone()
        ctrl = conn.execute("SELECT paused FROM control WHERE id = 1").fetchone()
        notices = conn.execute(
            "SELECT COUNT(*) AS n FROM notices WHERE status = 'queued'"
        ).fetchone()
        return {
            "channel_bound": ch is not None and ch["chat_id"] is not None,
            "channel_adapter": (
                ch["adapter"] if ch is not None and ch["chat_id"] is not None else None
            ),
            "paused": bool(ctrl["paused"]) if ctrl else False,
            "queued_notices": notices["n"],
        }
    except sqlite3.DatabaseError:
        # Not migrated yet, or not readable at all. Both are things `daemon status` and the
        # healthcheck have to survive: a damaged database is precisely when someone needs a
        # status report, and crashing here would take the whole report with it.
        return default
    finally:
        conn.close()


def _daemon_process_alive() -> bool:
    """Whether a daemon process is running right now, asked of the instance lock.

    The container's answer to "is it registered": there is no supervisor to ask, and the lock body
    names the live holder — which is the same question a `launchctl print` answers on a host.
    """
    return lock.is_pid_alive(lock.read_holder_pid(paths.lock_path()))


def gather_status(*, label: str | None = None, platform: Platform | None = None) -> Status:
    cfg = config.load()
    hb_age = heartbeat.age(paths.heartbeat_path())

    if deployment.is_container():
        # No job to interrogate, and no platform to resolve for one: Docker owns the process, so
        # its own liveness is the whole answer. Heartbeat freshness is reported the same way as on
        # a host, so a wedged loop still reads as wedged rather than as stopped.
        return _status(
            label=label or cfg.daemon_label or APP_LABEL,
            mode=deployment.CONTAINER,
            registered=_daemon_process_alive(),
            hb_age=hb_age,
            alive=_daemon_process_alive(),
        )

    platform = _resolve_platform(platform)
    label = label or cfg.daemon_label or platform.default_label()
    return _status(
        label=label,
        mode=cfg.daemon_mode,
        registered=platform.is_registered(label),
        hb_age=hb_age,
        alive=_daemon_process_alive(),
    )


def _status(*, label: str, mode: str, registered: bool, hb_age, alive: bool = False) -> Status:
    """The parts of the report that are the same wherever the daemon runs: what it has been
    doing, and what it is waiting on."""
    recent: list = []
    if paths.events_db().exists():
        conn = connect_reader(paths.events_db())
        try:
            all_events = query_events(conn)
            recent = all_events[-5:]
        finally:
            conn.close()

    snap = _channel_snapshot()
    return Status(
        label=label,
        mode=mode,
        registered=registered,
        heartbeat_age_sec=hb_age,
        process_alive=alive,
        recent_events=recent,
        channel_bound=snap["channel_bound"],
        channel_adapter=snap["channel_adapter"],
        paused=snap["paused"],
        queued_notices=snap["queued_notices"],
    )


# A daemon that has not written a heartbeat in this long is alive but not working — a wedged loop
# rather than a stopped one. The two want different answers from whoever is reading the status, so
# they are not both called "running".
_WEDGED_AFTER_SEC = 180.0


def _wedged(age: float | None) -> bool:
    return age is not None and age > _WEDGED_AFTER_SEC


def status(*, label: str | None = None, platform: Platform | None = None) -> int:
    st = gather_status(label=label, platform=platform)
    if st.registered and not st.process_alive:
        # The supervisor holds the job and nothing is running it. A clean stop leaves exactly this
        # — and it used to read as "running", which is how a dead daemon went unnoticed while a
        # seller tapped a button nothing was there to receive.
        state = "registered but NOT running — sellee daemon start"
    elif st.registered and _wedged(st.heartbeat_age_sec):
        state = f"running but not ticking — last heartbeat {st.heartbeat_age_sec:.0f}s ago"
    elif st.registered:
        state = "running"
    elif st.mode == MANUAL:
        state = "stopped (manual mode — sellee daemon start)"
    elif deployment.is_container():
        state = "stopped (the container is running but its worker is not)"
    else:
        state = "stopped"
    print(f"label:     {st.label}")
    print(f"mode:      {st.mode}")
    print(f"state:     {state}")
    if st.heartbeat_age_sec is None:
        print("heartbeat: none")
    else:
        print(f"heartbeat: {st.heartbeat_age_sec:.0f}s ago")
    print(f"channel:   {'bound' if st.channel_bound else 'not connected'}")
    print(f"paused:    {'yes' if st.paused else 'no'}")
    print(f"notices:   {st.queued_notices} queued")
    if st.recent_events:
        print("recent events:")
        for ev in st.recent_events:
            print(f"  {ev.kind}")
    return 0
