"""The OS-abstraction interface. Concrete platforms implement it; callers depend only here."""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path


class UnsupportedPlatform(Exception):
    """Raised by get_platform() when the host OS has no implementation yet."""


class RegistrationError(Exception):
    """A job could not be registered or started — or a foreign job stands where ours would go."""


# Embedded in every job definition we render, so a re-install/flip only ever touches our own and
# never silently replaces a foreign (e.g. legacy) daemon's job with the same label. Lives here
# because the platforms need it too: on Windows ours-vs-foreign must be decidable after
# registration, when the file we wrote is no longer what the scheduler reads.
MARKER = "Generated by selly-agent. DO NOT EDIT."


class Platform(ABC):
    """OS-specific operations the daemon needs. Keep this surface small.

    `home` is always passed in by paths.py rather than resolved here: home/XDG resolution is
    the sole responsibility of paths.py, so this module never reaches for it directly.
    """

    name: str = "base"

    # What render_supervisor's text must be written as. Not cosmetic: the tool that imports a
    # Windows task definition rejects one that is not UTF-16.
    definition_encoding: str = "utf-8"

    # Whether the directory holding job definitions belongs to us. False where it is the system's
    # own — ~/Library/LaunchAgents holds every application's, so an uninstall must leave it standing
    # even when ours was the only file in it.
    owns_job_directory: bool = False

    # True where the definition format cannot carry environment variables (Task Scheduler XML has
    # no such element). The supervisor then writes them to a companion file next to the definition
    # and names it in the job's arguments (--env-file), which the launcher applies on startup.
    environment_file: bool = False

    @abstractmethod
    def launch_agents_dir(self, home: Path) -> Path | None:
        """The per-user auto-start directory the supervisor reads at login.

        None where the OS has no such directory (registration is an API call, not a file
        placement); paths.py then keeps job definitions in our own config tree."""

    # --- supervisor (keep-alive job) ------------------------------------------------------

    @abstractmethod
    def default_label(self) -> str:
        """The default supervisor job label."""

    @abstractmethod
    def supervisor_filename(self, label: str) -> str:
        """The on-disk filename for a job config with this label."""

    @abstractmethod
    def render_supervisor(
        self,
        *,
        label: str,
        program_args: list[str],
        stdout_path: Path,
        stderr_path: Path,
        marker: str,
        environment: dict,
        start_at_login: bool,
        working_dir: Path | None = None,
    ) -> str:
        """Render the job definition (carries the marker so ours-vs-foreign is decidable).

        `environment` is pinned into the definition: a supervised job inherits nothing from the
        shell that installed it, so anything the daemon must see (XDG overrides) goes here. A
        platform whose format cannot carry it sets `environment_file` instead, and the caller
        delivers the same mapping through the companion file.

        `start_at_login` is asked because not every supervisor can express it by *where* the
        definition is put — a registered scheduled task persists across logins wherever its XML
        came from, so it has to say so in the definition itself.

        `working_dir` is the directory the job starts in, chosen by the caller; a platform whose
        definition has no such field ignores it."""

    @abstractmethod
    def register(self, config_path: Path) -> None:
        """Register + start the job from its config file (crash keep-alive active thereafter).

        Raises RegistrationError when the job could not be registered or started, or when a
        foreign job (no marker) already holds the label."""

    @abstractmethod
    def unregister(self, label: str) -> None:
        """Unregister the job; it stays stopped until re-registered."""

    @abstractmethod
    def is_registered(self, label: str) -> bool:
        """True if the supervisor currently has the job loaded."""
